#!/bin/bash

if (( $# != 3 )) || [[ "$1" != "dev" && "$1" != "prod" ]] || ! [[ "$3" =~ ^[0-9]+$ ]]; then
    echo "Error: Invalid arguments."
    echo
    echo "Usage: $0 [dev|prod] [instance os username] [webhook port: integer]"
    exit 1
fi

TIER=$1 OS_USERNAME=$2 WEBHOOK_PORT=$3 docker compose build --no-cache --build-arg OS_USERNAME=$2 && \
TIER=$1 OS_USERNAME=$2 WEBHOOK_PORT=$3 docker compose -p "natops-manager-$1" up -d --force-recreate && \
docker image prune --filter label=com.natops-manager.build=$1 --force